# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='time',
            new_name='timestamp',
        ),
    ]
