# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160505_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
