# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_location_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='Night',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sunset', models.DateTimeField()),
                ('sunrise', models.DateTimeField()),
                ('civil_dusk', models.DateTimeField()),
                ('civil_dawn', models.DateTimeField()),
                ('nautical_dusk', models.DateTimeField()),
                ('nautical_dawn', models.DateTimeField()),
                ('astronomical_dusk', models.DateTimeField()),
                ('astronomical_dawn', models.DateTimeField()),
                ('nadir', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
    ]
