# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-28 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_dusk_dawn_can_be_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoonPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('altitude', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
        migrations.RemoveField(
            model_name='night',
            name='nadir',
        ),
        migrations.AddField(
            model_name='night',
            name='midnight',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='night',
            name='moon_phase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='night',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='night',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
