# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_night_mjd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='counts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='period',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='night',
            name='mjd',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
