from django.conf.urls import patterns, include, url
from rest_framework import routers
from lmdb import views

router = routers.DefaultRouter() 
router.register(r'AnaBabelsberg', views.AnaBabelsbergViewSet)
router.register(r'AnaBbergSave', views.AnaBbergSaveViewSet)
router.register(r'AnaDahlem', views.AnaDahlemViewSet)
router.register(r'AnaDahlem2', views.AnaDahlem2ViewSet)
router.register(r'AnaDahlem2Old', views.AnaDahlem2OldViewSet)
router.register(r'AnaDahlem4Filterless', views.AnaDahlem4FilterlessViewSet)
router.register(r'AnaDahlem5Red', views.AnaDahlem5RedViewSet)
router.register(r'AnaDahlem6Green', views.AnaDahlem6GreenViewSet)
router.register(r'AnaDahlem7Blue', views.AnaDahlem7BlueViewSet)
router.register(r'AnaDahlemOld', views.AnaDahlemOldViewSet)
router.register(r'AnaFreienbrink', views.AnaFreienbrinkViewSet)
router.register(r'AnaFriedrichshagen', views.AnaFriedrichshagenViewSet)
router.register(r'AnaObservatorioDelTeide', views.AnaObservatorioDelTeideViewSet)
router.register(r'MarkproBabelsberg2', views.MarkproBabelsberg2ViewSet)
router.register(r'MarkproBerlinFriedrichshain', views.MarkproBerlinFriedrichshainViewSet)
router.register(r'MarkproBerlinSpandau', views.MarkproBerlinSpandauViewSet)
router.register(r'MarkproBerlinTreptow', views.MarkproBerlinTreptowViewSet)
router.register(r'Nutzung', views.NutzungViewSet)
router.register(r'SaveLocations', views.SaveLocationsViewSet)
router.register(r'SqmBabelsberg', views.SqmBabelsbergViewSet)
router.register(r'SqmBabelsberg3', views.SqmBabelsberg3ViewSet)
router.register(r'SqmDahlem', views.SqmDahlemViewSet)
router.register(r'SqmDahlem2', views.SqmDahlem2ViewSet)
router.register(r'SqmDahlem2Old', views.SqmDahlem2OldViewSet)
router.register(r'SqmDahlem2Save', views.SqmDahlem2SaveViewSet)
router.register(r'SqmDahlem3', views.SqmDahlem3ViewSet)
router.register(r'SqmDahlem4Filterless', views.SqmDahlem4FilterlessViewSet)
router.register(r'SqmDahlem5Red', views.SqmDahlem5RedViewSet)
router.register(r'SqmDahlem6Green', views.SqmDahlem6GreenViewSet)
router.register(r'SqmDahlem7Blue', views.SqmDahlem7BlueViewSet)
router.register(r'SqmDahlemOld', views.SqmDahlemOldViewSet)
router.register(r'SqmDahlemSave', views.SqmDahlemSaveViewSet)
router.register(r'SqmFreienbrink', views.SqmFreienbrinkViewSet)
router.register(r'SqmFriedrichshagen', views.SqmFriedrichshagenViewSet)
router.register(r'SqmLocations', views.SqmLocationsViewSet)
router.register(r'SqmLocationsDev', views.SqmLocationsDevViewSet)
router.register(r'SqmLocationsDev2', views.SqmLocationsDev2ViewSet)
router.register(r'SqmLocationsSave2', views.SqmLocationsSave2ViewSet)
router.register(r'SqmObservatorioDelTeide', views.SqmObservatorioDelTeideViewSet)

urlpatterns = patterns('',
    url(r'^', include(router.urls)),
)